[pytest]
minversion = 7.0

addopts =
    -ra
    --strict-markers
    --disable-warnings
    --maxfail=1
    --cov=rr2graph
    --cov-report=term-missing
    --cov-fail-under=90

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
